name: Build and push image
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/Hydrogen'

      - name: Install dependencies and generate Prisma types
        run: |
          npm install --legacy-peer-deps
          npm run generate

      - name: Build
        run: npm run build

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/scholarsome:latest,${{ secrets.DOCKER_USERNAME }}/scholarsome:${{ github.ref_name }}


